
language: objective-c
osx_image: xcode9.2

script:
  - xcodebuild -sdk iphonesimulator -project FlowControllerKit.xcodeproj -scheme FlowControllerKit -destination 'platform=iOS Simulator,name=iPhone 6,OS=11.2' CODE_SIGNING_REQUIRED=NO clean test

after_script:
  - bash <(curl -s https://codecov.io/bash)
  